### ISSUE TITLE
Supevisor Department information in the cover pages (adding a comment)

### ISSUE THREAD

**Issue by nunormont** [detiuaveiro/ua-thesis-template#23]
Regarding the `cover.tex` file,I have a suggestion. I couldn't change the department information of my supervisor, but then I solved the problem after 10 or 15 minutes.

I noticed that the supervisor's department was by by default "Departamento de Eletrónica e Comunicações", as I quote here, from the page 4 of the `cover.pdf`:
**Dissertação apresentada à Universidade de Aveiro para cumprimento dos requisi-
tos necessários à obtenção do grau de Mestre em Engenharia de Computadores e
Telemática, realizada sob a orientação científica do Doutor Tiago C. A. Oliveira,
Professor auxiliar do Departamento de Eletrónica, Telecomunicações e Informá-
tica da Universidade de Aveiro, e do (...)**

And when I changed the supervisor line of `cover.tex` to this:
`\Supervisor{Tiago C. A. Oliveira}{auxiliar}{do Departamento de Física}{da Universidade de Aveiro}`
I got an error when I compiled the cover file. Then I solved the problem because I realised that I had to change the department information to `fis` on the line `\usepackage[engineering,fis]{uaThesisTemplate}`

So, my suggestion is for you to put a comment on that line on the fact that we have to select the department first (the emphasis of the department information is at the moment less relevant, at first sight, due to the fact that the department is, by the new rule of Univ. of Aveiro, not printed in the first page of the cover.

**Comment by fabiomaia** [comment]
Thanks for the comment! Would you like to contribute this with a pull request?
