### ISSUE TITLE
How to change the language of "code block"?

### ISSUE THREAD

**Issue by nunormont** [detiuaveiro/ua-thesis-template#24]
I changed the standard language from portuguese to english in `matter.tex` and as expected the figure names changed from "Figura" to "Figure", and the chapter names from "Capitulo" to "Chapter". But when I create a code block like this:
```
\begin{listing}
\begin{verbatim}
(code ...)
\end{verbatim}
\caption{Code description}
\label{code_lbl}
\end{listing}
```
The label still is displayed in portuguese. Instead of "Code 1: Code description" it is still "Código 1: Code description". I tried to see if I could change it in `custom_theme.tex` and in `uaThesisTemplate.sty`, but haven't found anything.

How can I make that label change from portuguese to english?

**Comment by fabiomaia** [comment]
https://github.com/detiuaveiro/ua-thesis-template/issues/17

**Comment by nunormont** [comment]
Thanks @fabiomaia.
