### ISSUE TITLE
Print page number in correct place + subsubsection formatting

### ISSUE THREAD

**Issue by manuelpereira96** [detiuaveiro/ua-thesis-template#33]
Hi guys,

I'm quite new to LaTeX, so it is quite possible these are dumb questions. 

**Number**
I noticed that the page numbers appear in the bottom right side of the page, while for even pages the number appears in the middle. Is there a way to solve this?

**Subsubsection**
Is there a way to change the formatting of the subsubsection? They appear in italics. I would like to have them in bold and a bit larger.

Btw, I'm using this template in Overleaf in case this are problems specific to Overleaf.

**Comment by rj-jesus** [comment]
To control these settings you can modify the chapter and page style you're using. By default [a chapter style called `veelo`](https://github.com/detiuaveiro/ua-thesis-template/blob/9a30602dcbc35486b4cc141be1776f16e9cf4d09/matter.tex#L247) and [the `plain` page style](https://github.com/detiuaveiro/ua-thesis-template/blob/9a30602dcbc35486b4cc141be1776f16e9cf4d09/matter.tex#L265) are used, but there's also [a custom theme showing you how to define your own theme](https://github.com/detiuaveiro/ua-thesis-template/blob/master/custom-theme.tex).

In particular, to change the section styling you can use the commands below:
```
% Section style
\setsecheadstyle{\normalfont\Large\rmfamily\mdseries\upshape\raggedright}
\setsubsecheadstyle{\normalfont\large\rmfamily\mdseries\upshape\raggedright}
\setsubsubsecheadstyle{\normalfont\normalsize\rmfamily\mdseries\upshape\raggedright}

\setbeforesecskip{3.5ex}
\setaftersecskip{2ex}
\setbeforesubsecskip{3.5ex}
\setaftersubsecskip{2ex}
\setbeforesubsubsecskip{3.5ex}
\setaftersubsubsecskip{2ex}
```

To change the numbering, take a look at the documentation of [`memoir`](https://mirror.apps.cam.ac.uk/pub/tex-archive/macros/latex/contrib/memoir/memman.pdf), in particular §7 (e.g. try using `\pagestyle{headings}`).

**Comment by avzuquete** [comment]
> Hi guys,
> 
> I'm quite new to LaTeX, so it is quite possible these are dumb questions.
> 
> **Number** I noticed that the page numbers appear in the bottom right side of the page, while for even pages the number appears in the middle. Is there a way to solve this?
> 
> **Subsubsection** Is there a way to change the formatting of the subsubsection? They appear in italics. I would like to have them in bold and a bit larger.
> 
> Btw, I'm using this template in Overleaf in case this are problems specific to Overleaf.

Bug (festure?) of the veelo chapter style (check matter.tex).
Add the following line after choosing that style:

\makeoddfoot{plain}{}{\thepage}{}
