### ISSUE TITLE
More than one co-supervisor not  supported

### ISSUE THREAD

**Issue by Jpfonseca** [detiuaveiro/ua-thesis-template#40]
Currently, the template does not support more than one co-supervisor.  
I can take this one.

**Comment by jpbarraca** [comment]
Do you have a fix for it?

**Comment by Jpfonseca** [comment]
It's on my todo list. Will up date soon

**Comment by danielvcorreia** [comment]
This issue can be closed. It was resolved in #46

**Comment by Jpfonseca** [comment]
True. Closed
