### ISSUE TITLE
Thesis rejected because of the Quote page

### ISSUE THREAD

**Issue by ruilvo** [detiuaveiro/ua-thesis-template#48]
I had my thesis rejected because of the Quote page. 
In this template, the quote is put as the second cover page. This includes all the title information, as it just a variation of the cover, with a cover instead of a figure. 
This got my document rejected.
Turns out the quote is supposed to be on an empty page, last thing in the cover pages (after the abstracts).

**Comment by jtsimoes** [comment]
Quote was removed on 42b16ba 

The only thing left to do is remove the `\Quote` command, which is no longer needed, and this issue can be closed

https://github.com/detiuaveiro/ua-thesis-template/blob/442912ca7671f50fc8c1aed51985954a06fe1533/uaThesisTemplate.sty#L36
